feat: __repr__ method to Schema, Row, Column, SupervisedDataset & Table; summary() to Column & Table
lars-reimann/Safe-DS pull request #333
Opened 2023-01-20 14:36 UTC by GideonKoenig

Closes #319.

### Summary of Changes

- Added `__str__()`, `__repr__()` and `_ipython_display_()` methods to the classes `Table`, `Column`, `Row`, `TableSchema`and `SupervisedDataset`.
- Added the method `summary()` to the `Table` class
- Changed the raised error in some of the ColumnStatistics methods from `TypeError` to `NonNumericColumnError`
- Moved the methods `idness()` and `stability()` from the class `Column` to `ColumnStatistics`
  - Refactored the test accordingly

### Testing Instructions

Create an instance of one of the mentioned classes and either call the print method on it or use the jupyter notebook interactive display method to visualize it in a prettier way.

2023-01-20 15:42 UTC, WinPlay02 reviewed
get_column_names is duplicated: Table, Row (already exists in TableSchema)

2023-01-21 02:18 UTC, dorianheidorn submitted a review, later dismissed

2023-01-27 08:40 UTC, Marsmaennchen221 requested changes

2023-01-27 08:40 UTC, Marsmaennchen221 commented on Runtime/safe-ds/tests/data/_table/test__str__.py
> +    assert table1.schema == row.schema
Wieso ist dieser Test in der `__str__` test Datei? Ihr greift hier doch nicht auf die `__str__` zu?

2023-01-27 09:18 UTC, Marsmaennchen221 approved these changes

2023-01-27 09:40 UTC, WinPlay02 approved these changes

2023-01-27 09:40 UTC, merged